### ISSUE TITLE
User Story: Lesson 1 - Tasks

### ISSUE THREAD

**Issue by tomdu3** [tomdu3/python-course-material#2]
### USER STORY
As a ***student***, I want to ***have a clearly defined weekly task***, so that I can ***code the weekly assignment.***

***

### ACCEPTANCE CRITERIA

- [x] Weekly tasks are defined in an md file.
- [x] Inputs and Outputs are clearly defined
- [x] Python needs to be installed on the computer
- [x] VS CODE or other IDE should be installed on the computer
- [x] hello world has to be in a file and executed
- [x] bio code should be in a file and executed
- [x] student needs to send the screenshots of the the files and executions

***

### TASKS

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

***
